name: 'Bang9'
description: 'Issues to README.md'
author: 'Hyungu Airen Kang'
inputs:
  token:
    required: true
    description: 'GitHub Personal access token here'
  starts_with:
    required: false
    description: 'Filter issues by title.startsWith'
    default: ''
  owner_only:
    required: false
    description: 'Filter issues by owner'
    default: 'false'
  timezone:
    required: false
    description: 'Timezone for date format'
runs:
  using: 'node16'
  main: 'dist/index.js'
